### ISSUE TITLE
Extend search functionality (`3.6.1 Note`)

### ISSUE THREAD

**Issue by pdaengeli** [cceh/mea-atom-installation#11]
Searching is currently possible on the fields `Title`, `Archival history`, `Scope and content`, `Extent and medium`, `Subject access points`, `Name access points`, `Place access points`, `Identifier`, and `Reference code`.

In order to use AtoM as a research tool it essential to also search `Notes` and `Archivist's notes`. 

Could these fields be included in the search? In a way that has a chance to be compatible with forthcoming AtoM releases?

We could also request this to be added to AtoM in general, but I can imagine that folks at Artefactual are reluctant to the idea (esp. regarding `Archivist's notes`, that is in the sense of ISAD(G) less a note of an archivist (gen. objectivus) than a note about an archivist (gen. subjectivus) [(cf. archives.memorix.nl)](https://archives.memorix.nl/standards/ISAD(G)#3.7.1), hence its situation under 3.7 (`Description control area`).

**Comment by textloop** [comment]
Hallo @strec:
Heute habe ich mit der aktuellen Installation, getestet:
Das Problem ist noch existent. Unerheblich scheint zu sein, ob das Feld über die Benutzeroberfläche als "sichtbar" oder "unsichtbar" klassifiziert wurde. Aufgefallen ist mir dass es im Dropdown-Menü der Suche noch in englischer Sprache angegeben wird. Kann das damit zu tun haben?

Für die Probleme die erweiterte Suche überhaupt zu öffnen und dass das Feld Signatur im Dropdown-Menü zweimal vorkommt eröffne ich ein zusätzliches Ticket, dass ihr euch dann benefalls ansehen müsstet.

**Comment by textloop** [comment]
Test results: 2015-01-2015 installation
Field "Anmerkungen" is included in extended search, but search results are not limited to the field "Anmerkungen".
Example search for "Rosenthal" within "Anmerkungen": 
10 results
but some of them do not even posess a "Anmerkung" and some have no "Rosenthal" within Anmerkung but within the title. 
.../a/index.php/mea-gga-i-bw-1936-03-21
.../a/index.php/mea-gga-i-bw-1933-06-06

@strec ?

**Comment by strec** [comment]
It is only a typo. There is a "break;" missing here:
https://github.com/cceh/atom/blob/mea/apps/qubit/modules/search/actions/advancedAction.class.php#L384
So at the moment it is running through the "_all"-case, too.
And then the default of searching all fields.

**Comment by textloop** [comment]
Great! Thank you.

**Comment by textloop** [comment]
HI @strec:
the latest installation (04-02-2015) shows no search results for "Rosenthal" limited to the field "Anmerkungen". Could you please check on that again?

**Comment by textloop** [comment]
To find a solution for this problem:
Could we simply delete the field "Anmerkungen" from the dropdown menu? The search goes through "Anmerkungen" if "in allen Feldern" is chosen.
For example search for "Mitteilungen" in all fields. You get a result for `../mea-gga-i-bw-1936-05-24-1` where "Mitteilungen" is exclusively in field "Anmerkungen". 
It does what it should do, only the limitation to "Anmerkungen" is not possible - plus misleading for most of the users, who can not see "Anmerkungen" because it is hidden.

**Comment by strec** [comment]
This line
https://github.com/cceh/atom/blob/mea/apps/qubit/modules/search/actions/advancedAction.class.php#L382
must be written like this:
$queryField->setFields(arElasticSearchPluginUtil::getI18nFieldNames('generalNotes.i18n.%s.content'));

I changed it on the server to test it out. It works.

As far as the misleading part of Anmerkungen being hidden to to users not being administrator or editor is concerned, we could easily implement it in a way, that only administrators and editors see the extra option "Anmerkungen" in the advanced search options. I just testet it, too.

side-note: Only "Mitteilung" occurs in the Anmerkungen.

**Comment by textloop** [comment]
Sounds good. If it can be easily done, please hide field "Anmerkungen" for users that are no admins or editors. Please check on issue #53 , could this be solved in that way too? (the ones carrying "?" in the german version, should be excluded from the list of possible search filters)

**Comment by gioele** [comment]
Implemented in cceh/atom#7.
