### ISSUE TITLE
Dropdown menu for extended search shows erroneous entries

### ISSUE THREAD

**Issue by textloop** [cceh/mea-atom-installation#43]
Dropdown menu shows "signature" twice and contains not translated name vor Anmerkungen (General note(s)

This issue was transferred from #11

**Comment by gioele** [comment]
There are two different terms translated as "Signatur" in `plugins/sfMeaPlugin/i18n/de/messages.xml`.

**Comment by gioele** [comment]
The two English terms translated as "Signatur" are

* "Reference code",
* "Identifier".

What should be their respective translations?

**Comment by textloop** [comment]
- "Reference code" should be "Signatur"

and 
- "Identifier" should be "ID"

**Comment by textloop** [comment]
@gioele: The double "Signatur"  is still existant in the current installation (16-01-2015). And "General note(s)" is still not translated.

**Comment by textloop** [comment]
Hi @gioele, I found the solutionaccidentally! The correct translations for Reference code and Identifier could simply be realized using the translation feature "Translate user interface. This problem was caused by myself or Peter while translating.
