### ISSUE TITLE
Users and groups can not be fully edited using german 

### ISSUE THREAD

**Issue by textloop** [cceh/mea-atom-installation#44]
Problems while using the german interface:

When creating an new user, no group can be chosen.
<http://meister-eckhart-archiv.uni-koeln.de/a/index.php/user/add>

List of groups does not show the name of the group but some ID:
http://meister-eckhart-archiv.uni-koeln.de/a/index.php/aclGroup/list

**Comment by gioele** [comment]
This happens because there are no translations of the group names in `data/fixtures/acl.yml`

These are the default groups that must be translated:

```
  en: anonymous
  en: authenticated
  en: administrator
  en: editor
  en: contributor
  en: translator
```

**Comment by textloop** [comment]
en: anonymous = Besucher (nicht eingeloggt)
en: authenticated = Besucher (eingeloggt)
en: administrator = Administrator
en: editor = Bearbeiter (volle Rechte)
en: contributor = Bearbeiter (eingeschränkte Rechte)
en: translator = Übersetzer
