### ISSUE TITLE
Create email adresses linked to new mea URL

### ISSUE THREAD

**Issue by textloop** [cceh/mea-atom-installation#50]
Create new email adress for editorial feedback and team members. See my email for further information.

Are shorter versions desirable?

**Comment by jblumtritt** [comment]
it is not possible to create email addresses that include the subdomain with our hosting service.
think of something along the lines of: meister-eckhart-archiv@uni-koeln.de or webmaster-mea@uni-koeln.de

only natural persons may apply for an email address. For other purposes (project  feedback/webmaster) you can create a mailinglist that forwards to one or many email addresses. Mailinglist addresses always have the following form: listname@uni-koeln.de.

**Comment by textloop** [comment]
So we could create a mailinglist like "meister-eckhart-archiv@uni-koeln.de" and forward incoming eailsls to the editors at Meister Eckhart Archiv?  Is there a webinterface we could use to apply for the adresses or do we have to write an email to the Rechenzentrum?

**Comment by pdaengeli** [comment]
Check http://rrzk.uni-koeln.de/mailinglisten.html or more specifically http://rrzk.uni-koeln.de/antrag-kontaktadresse.html.

**Comment by textloop** [comment]
Notiz: Für Maxime Admin-Zugang anlegen mit neuer Adresse

**Comment by textloop** [comment]
Wird vom MEA-Team selbst beantragt
