### ISSUE TITLE
modifications in MEA navigation menu

### ISSUE THREAD

**Issue by textloop** [cceh/mea-atom-installation#52]
Maxime: 

in der oberen Ebene: „Forschungskatalog“ durch „Bibliothek“ ersetzen; unter diesem Ordner: a) „zum MEA“ in „Literatur zum Meister-Eckhart-Archiv“ umbenennen und b) „Meister-Eckhart-Forschung“ durch „Sekundärliteratur über Meister Eckhart“ ersetzen.

**Comment by textloop** [comment]
@gioele: I understood, for modifications in the mea navigation menu there is no new installation necessary? Could I do modifications like this by myself? I'm kind of excpecting more will follow!

**Comment by textloop** [comment]
here is one more: DIaporama shoulld be deleted from the navigation menu.
@gioele : Could you give me a hint, where these modification can be realized?

**Comment by textloop** [comment]
and another one: 
„Forschungskatalog“ should be „Bibliothek“

**Comment by gioele** [comment]
The source code for the menu is in https://github.com/cceh/atom/blob/mea/apps/qubit/templates/_mea_menu.php but I fear that every change will require some adjustments also to the CSS, because the CSS rules are quite tailored to the exact current HTML code.

**Comment by gioele** [comment]
And yes, a new installation is not needed, just a `git pull` or `git checkout` of the modified sources.

**Comment by textloop** [comment]
Ok, I see, better to leave this task to you.

Could you please take care of the following modifications:
- Rename "Forschungskatalog" to "Bibliothek"
- Subordinate to "Forschungskatalog": „Zum MEA“ should be „Literatur zum Meister-Eckhart-Archiv“
- Subordinate to "Forschungskatalog": „Meister-Eckhart-Forschung“ should be „Sekundärliteratur über Meister Eckhart“
-  Subordinate to „Über Meister Eckhart“: please delete „Diaporama“.

**Comment by gioele** [comment]
One problem: we cannot change the _names_ of the static pages, so "Bibliothek" must be a link to `a/index.php/Forschungskatalog`, similarly "Literatur zum Meister-Eckhart-Archiv" will be a link to `a/index.php/zum-mea`. Not a big problem in the second case, may be a problem in the first case.

**Comment by textloop** [comment]
Couldn't we simply create  an new static page called "Bibliothek"? And leave the old "Forschungskatalog" unused?

**Comment by gioele** [comment]
Makes sense :+1:

**Comment by gioele** [comment]
I made the needed changes to the HTML menu but not committed them. I will now create the missing pages.
