### ISSUE TITLE
"Beschreibung der Seite" in Einstellungen/Seiteninformation can not be modified

### ISSUE THREAD

**Issue by textloop** [cceh/mea-atom-installation#57]
For the final installation 
Einstellungen > Seiteninformationen >  Beschreibung der Seite
should be shortened from
"Meister-Eckhart-Archiv (Test)" to "Meister-Eckhart-Archiv"
`.../a/index.php/settings/list`

Using the field for new contents seem to have no impact.

**Comment by textloop** [comment]
![mea-seiteninformation](https://cloud.githubusercontent.com/assets/7046115/6104398/7c6d5618-b04d-11e4-856b-02779aac7c3f.jpg)

**Comment by textloop** [comment]
The official AtoM demo pages shows: AtoM 2.0 demo site, hosted by Artefactual Systems

**Comment by gioele** [comment]
Saved in the official installation instructions in the Wiki.
