### ISSUE TITLE
Remaining translation gaps

### ISSUE THREAD

**Issue by textloop** [cceh/mea-atom-installation#60]
I checked as a user not authenticated, these are the last remaining translation gaps.
1. Find out where "Narrow your results" and "unique records" can be translated.
   http://.../a/index.php/actor/browse
2. Translate "Browse" with "Zugriff auf" 
   http://.../a/index.php/subjects
3. Criteria for narrow your results by "Archivtyp":
   http://.../a/index.php/repository/browse
   I only found a possibility to translate "LOCALITY"/"Örtliche Lage" here.

**Comment by gioele** [comment]
What are the suggested translations for
- "Narrow your results by" (`data/fixtures/settings.yml`)
- "Unique records" (`apps/qubit/i18n/de/messages.xml`)
- "Show all" (`apps/qubit/i18n/de/messages.xml`)

?

**Comment by textloop** [comment]
That would be:
- "Narrow your results by" (`data/fixtures/settings.yml`) = "Treffer einschränken mit"
- "Unique records" (`apps/qubit/i18n/de/messages.xml`) = "Unterscheidbare Datensätze"
- "Show all" (`apps/qubit/i18n/de/messages.xml`)= "Alle anzeigen"

Sorry for missing out on that.

**Comment by textloop** [comment]
1. and 2. are closed - 3. is still open!

**Comment by textloop** [comment]
These are the translations for 3.:
GEOGRAPHIC REGION: Land
GEOGRAPHIC SUBREGION: Bundesland
THEMATIC AREA: Themen/Gegenstände
