### ISSUE TITLE
Some intems in "Suchfilter" (within "Erweiterte Suche") lead to not matching items

### ISSUE THREAD

**Issue by textloop** [cceh/mea-atom-installation#62]
Two problems with "Suchfilter" "Verzeichnungsebene" popped up: 
1. "Sammlung" is listet twice. One is correctly leading to "Meister-Eckhart-Archiv", the other one  finds no matches. 
2. "Akte" leads to 8 false items. 
   This needs explanation: Maxime pointed me to the fact, that all 8 items within 
   http://meister-eckhart-archiv.uni-koeln.de/a/index.php/mea-gga-i-so were classified as "Akte", although there actually are "Einzelstücke". I have corrected each item to "Einzelstück". But still three all of them show up as "Akte". I already tried deleting cookies. 
   Maby this is beacause the search index is not renewed?

**Comment by gioele** [comment]
Right now they do not show up as "Akte" in the linked page. Were you referring to another page?

Anyway, yes, there the search results are cached and the cache takes a bit (hours) to expire. It looks like the cache is not invalidated as soon as an item is changed or removed.

**Comment by textloop** [comment]
![image](https://cloud.githubusercontent.com/assets/7046115/7225324/6e81fc12-e73d-11e4-9717-a2049634d15e.png)

**Comment by textloop** [comment]
The first 8 items should no longer be listed here. (I'm using Chrome, Version 42.0.2311.90 m)

**Comment by textloop** [comment]
Second Problem was caused by a missing directory with elasticsearch data on the server. First problem is still existing and was transfered to issue #65
