### ISSUE TITLE
Adding new access points for "Themen/Gegenstände" does no longer work

### ISSUE THREAD

**Issue by textloop** [cceh/mea-atom-installation#63]
Although there was no new installtion in the meantime some features do no longer work
 (but surely did the last time I checked in February?)

 Today I have created a new term "Briefwechsel" and two subterms "Jahrgang 1932" and "Jahrgang 1933" to be able to group letters into age-groups using access points.
http://.../a/index.php/briefwechsel
If I try to add one of these to an item/Einzelstück, the link leads to no results. 

Look for "Zugriffspunkt" in 
http://.../a/index.php/mea-gga-i-bw-1932-12-23. 
Clicking on the "Zugriffspunkt: Themen/Gegenstände" leads to 
http://.../a/index.php/jahrgang-1932.
While "Zugriffspunkt Namen" is still working.

**Comment by textloop** [comment]
This seems to be linked to further problems: 
- Look for cryptic entries in "Narrow you results: Gegenstand" on 
  http://.../a/index.php/informationobject/browse
- unauthenticicated users can't see the new Zugriffspunkt "Briefwechsel"

**Comment by gioele** [comment]
This problem

> - unauthenticicated users can't see the new Zugriffspunkt "Briefwechsel"

makes me think that this may have been caused by the latest modification made by @strec to the search code. @strec, any idea?

**Comment by textloop** [comment]
Solved! Problems were based on missing elasticsearch's data repository.
