### ISSUE TITLE
new authority records for persons do not show up within list of persons

### ISSUE THREAD

**Issue by textloop** [cceh/mea-atom-installation#64]
This might linked to #63:

I created a new authority record for a person: 
http:/.../a/index.php/klibansky-r
but it is not showing up in 
http://meister-eckhart-archiv.uni-koeln.de/a/index.php/actor/browse
but it works as a "Zugriffspunkt" on level of items:
http://.../a/index.php/mea-gga-i-bw-1932-12-23

**Comment by gioele** [comment]
Much likely related to the search problem that also caused #63.

**Comment by textloop** [comment]
Solved! Problems were based on missing elasticsearch's data repository.
