### ISSUE TITLE
Uploads: max. filesize

### ISSUE THREAD

**Issue by pdaengeli** [cceh/mea-atom-installation#71]
Maxime reports that he cannot upload files as small as 3 MB. 

The ´upload_max_filesize´ setting of the web server allows 128 MB. What else may cause this limitation?

**Comment by textloop** [comment]
Did you check on the Upload-settings for Meister-Eckhart-Archiv am Thomas-Institut?
<.../a/index.php/fkk9-btfd-ghcb#>?

**Comment by pdaengeli** [comment]
Thanks, I wasn't aware of that setting at `/a/index.php/fkk9-btfd-ghcb`. I now set it to 50 GB and altered `Default archiv upload limit (GB)` from `-1` to `1 GB` at `/a/index.php/settings/list`.

However uploads still fail (the size of the test image was just 77 KB).

**Comment by pdaengeli** [comment]
Uploads are possible using Chrome, but not using (some versions of) Firefox or Safari.

**Comment by gioele** [comment]
The problems with Firefox and uploads are known. I think there a closed ticket about them.

**Comment by textloop** [comment]
See issue #56 
I added this problem to our project documentation.
