### ISSUE TITLE
upload_max_filesize on the web server is limited again

### ISSUE THREAD

**Issue by textloop** [cceh/mea-atom-installation#80]
The ´upload_max_filesize´ setting of the web server should allow 128 MB agbain. 

@Sviat2513 will write an email to the RRZK, asking them to raise the upload limit to 128 MB again.

**Comment by Sviat2513** [comment]
I did it and now waiting on answer from rrzk.

**Comment by textloop** [comment]
the RRZK raised the upload limit to 128 MB on  09-11-2015.
